"""add doctor slots table

Revision ID: 2d120f291f02
Revises: 8a1f5edf0659
Create Date: 2026-09-16 15:23:53.515905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d120f291f02'
down_revision: Union[str, Sequence[str], None] = '8a1f5edf0659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('available', 'booked')", name='ck_doctor_slots_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_slots_doctor_id_start_time', 'doctor_slots', ['doctor_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_slots_doctor_id_start_time', table_name='doctor_slots')
    op.drop_table('doctor_slots')
    # ### end Alembic commands ###
